### ISSUE TITLE
注册的时候，按验证后台报BadRequestError错误

### ISSUE THREAD

**Issue by qinkangwu** [yuu2lee4/library_be#2]
{ BadRequestError: This library (validator.js) validates strings only
    at Object.throw (/Users/admin/reduxDemo/koa2_demo/library_be/node_modules/koa/lib/context.js:93:11)
    at /Users/admin/reduxDemo/koa2_demo/library_be/node_modules/koa-scheme/index.js:75:22
    at Array.forEach (native)
    at /Users/admin/reduxDemo/koa2_demo/library_be/node_modules/koa-scheme/index.js:67:38
    at Array.forEach (native)
    at Object.scheme (/Users/admin/reduxDemo/koa2_demo/library_be/node_modules/koa-scheme/index.js:63:14)
    at scheme.next (<anonymous>)
    at onFulfilled (/Users/admin/reduxDemo/koa2_demo/library_be/node_modules/co/index.js:65:19)
    at /Users/admin/reduxDemo/koa2_demo/library_be/node_modules/co/index.js:54:5
    at Promise (<anonymous>)
    at Object.co (/Users/admin/reduxDemo/koa2_demo/library_be/node_modules/co/index.js:50:10)
    at converted (/Users/admin/reduxDemo/koa2_demo/library_be/node_modules/koa-convert/index.js:17:15)
    at dispatch (/Users/admin/reduxDemo/koa2_demo/library_be/node_modules/koa-compose/index.js:42:32)
    at next (/Users/admin/reduxDemo/koa2_demo/library_be/node_modules/koa-compose/index.js:43:18)
    at /Users/admin/reduxDemo/koa2_demo/library_be/node_modules/koa-session-minimal/dist/session.js:72:13
    at Generator.next (<anonymous>)
  message: 'This library (validator.js) validates strings only' }

报错信息，求看一下，邮箱填写是正确的

**Comment by yuu2lee4** [comment]
把config/scheme.js第17行 "checkUser": validator.isBoolean  注释掉
